[package]
name = "nuttx"
version = "0.1.0"
edition = "2024"

[dependencies]
libc = { version = "0.2", default-features = false, features = [] }
kconfig = { path = "kconfig" }

[build-dependencies]
bindgen = "0.71.1"
